# Generated by Django 2.1 on 2019-06-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(choices=[('', '変換方法を選んでください'), ('グレースケール', 'グレースケール'), ('モザイク', 'モザイク'), ('フェイスモザイク', 'フェイスモザイク'), ('モザイクgif', 'モザイクgif')], max_length=255, verbose_name='画像変換方法'),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(upload_to='documents/', verbose_name='画像選択'),
        ),
    ]
